import {
  createVoidElementFactory,
  createElementFactory
} from './element.js'

export const svg = /* @__PURE__ */ createElementFactory('svg')
export const a = /* @__PURE__ */ createElementFactory('a')
export const animate = /* @__PURE__ */ createVoidElementFactory('animate')
export const animateMotion = /* @__PURE__ */ createVoidElementFactory('animateMotion')
export const animateTransform = /* @__PURE__ */ createVoidElementFactory('animateTransform')
export const circle = /* @__PURE__ */ createVoidElementFactory('circle')
export const clipPath = /* @__PURE__ */ createElementFactory('clipPath')
export const defs = /* @__PURE__ */ createElementFactory('defs')
export const desc = /* @__PURE__ */ createElementFactory('desc')
export const ellipse = /* @__PURE__ */ createVoidElementFactory('ellipse')
export const feBlend = /* @__PURE__ */ createElementFactory('feBlend')
export const feColorMatrix = /* @__PURE__ */ createElementFactory('feColorMatrix')
export const feComponentTransfer = /* @__PURE__ */ createElementFactory('feComponentTransfer')
export const feComposite = /* @__PURE__ */ createElementFactory('feComposite')
export const feConvolveMatrix = /* @__PURE__ */ createElementFactory('feConvolveMatrix')
export const feDiffuseLighting = /* @__PURE__ */ createElementFactory('feDiffuseLighting')
export const feDisplacementMap = /* @__PURE__ */ createElementFactory('feDisplacementMap')
export const feDistantLight = /* @__PURE__ */ createElementFactory('feDistantLight')
export const feDropShadow = /* @__PURE__ */ createElementFactory('feDropShadow')
export const feFlood = /* @__PURE__ */ createElementFactory('feFlood')
export const feFuncA = /* @__PURE__ */ createElementFactory('feFuncA')
export const feFuncB = /* @__PURE__ */ createElementFactory('feFuncB')
export const feFuncG = /* @__PURE__ */ createElementFactory('feFuncG')
export const feFuncR = /* @__PURE__ */ createElementFactory('feFuncR')
export const feGaussianBlur = /* @__PURE__ */ createElementFactory('feGaussianBlur')
export const feImage = /* @__PURE__ */ createElementFactory('feImage')
export const feMerge = /* @__PURE__ */ createElementFactory('feMerge')
export const feMergeNode = /* @__PURE__ */ createElementFactory('feMergeNode')
export const feMorphology = /* @__PURE__ */ createElementFactory('feMorphology')
export const feOffset = /* @__PURE__ */ createElementFactory('feOffset')
export const fePointLight = /* @__PURE__ */ createElementFactory('fePointLight')
export const feSpecularLighting = /* @__PURE__ */ createElementFactory('feSpecularLighting')
export const feSpotLight = /* @__PURE__ */ createElementFactory('feSpotLight')
export const feTile = /* @__PURE__ */ createElementFactory('feTile')
export const feTurbulence = /* @__PURE__ */ createElementFactory('feTurbulence')
export const filter = /* @__PURE__ */ createElementFactory('filter')
export const foreignObject = /* @__PURE__ */ createElementFactory('foreignObject')
export const g = /* @__PURE__ */ createElementFactory('g')
export const image = /* @__PURE__ */ createVoidElementFactory('image')
export const line = /* @__PURE__ */ createVoidElementFactory('line')
export const linearGradient = /* @__PURE__ */ createElementFactory('linearGradient')
export const marker = /* @__PURE__ */ createElementFactory('marker')
export const mask = /* @__PURE__ */ createElementFactory('mask')
export const metadata = /* @__PURE__ */ createElementFactory('metadata')
export const mpath = /* @__PURE__ */ createVoidElementFactory('mpath')
export const path = /* @__PURE__ */ createVoidElementFactory('path')
export const pattern = /* @__PURE__ */ createElementFactory('pattern')
export const polygon = /* @__PURE__ */ createVoidElementFactory('polygon')
export const polyline = /* @__PURE__ */ createVoidElementFactory('polyline')
export const radialGradient = /* @__PURE__ */ createElementFactory('radialGradient')
export const rect = /* @__PURE__ */ createVoidElementFactory('rect')
export const script = /* @__PURE__ */ createElementFactory('script')
export const set = /* @__PURE__ */ createVoidElementFactory('set')
export const stop = /* @__PURE__ */ createElementFactory('stop')
export const style = /* @__PURE__ */ createElementFactory('style')

const svgSwitch = /* @__PURE__ */ createElementFactory('switch')

export { svgSwitch as switch }

export const symbol = /* @__PURE__ */ createElementFactory('symbol')
export const text = /* @__PURE__ */ createElementFactory('text')
export const textPath = /* @__PURE__ */ createElementFactory('textPath')
export const title = /* @__PURE__ */ createElementFactory('title')
export const tspan = /* @__PURE__ */ createElementFactory('tspan')
export const use = /* @__PURE__ */ createVoidElementFactory('use')
export const view = /* @__PURE__ */ createElementFactory('view')
