import type * as Attributes from './attributes.js'

export interface IntrinsicElements {
  // HTML
  a: HTMLAnchorElement
  abbr: HTMLElement
  address: HTMLElement
  area: HTMLAreaElement
  article: HTMLElement
  aside: HTMLElement
  audio: HTMLAudioElement
  b: HTMLElement
  base: HTMLBaseElement
  bdi: HTMLElement
  bdo: HTMLElement
  big: HTMLElement
  blockquote: HTMLQuoteElement
  body: HTMLBodyElement
  br: HTMLBRElement
  button: HTMLButtonElement
  canvas: HTMLCanvasElement
  caption: HTMLElement
  center: HTMLElement
  cite: HTMLElement
  code: HTMLElement
  col: HTMLTableColElement
  colgroup: HTMLTableColElement
  data: HTMLDataElement
  datalist: HTMLDataListElement
  dd: HTMLElement
  del: HTMLModElement
  details: HTMLDetailsElement
  dfn: HTMLElement
  dialog: HTMLDialogElement
  div: HTMLDivElement
  dl: HTMLDListElement
  dt: HTMLElement
  em: HTMLElement
  embed: HTMLEmbedElement
  fieldset: HTMLFieldSetElement
  figcaption: HTMLElement
  figure: HTMLElement
  footer: HTMLElement
  form: HTMLFormElement
  h1: HTMLHeadingElement
  h2: HTMLHeadingElement
  h3: HTMLHeadingElement
  h4: HTMLHeadingElement
  h5: HTMLHeadingElement
  h6: HTMLHeadingElement
  head: HTMLHeadElement
  header: HTMLElement
  hgroup: HTMLElement
  hr: HTMLHRElement
  html: HTMLHtmlElement
  i: HTMLElement
  iframe: HTMLIFrameElement
  img: HTMLImageElement
  input: HTMLInputElement
  ins: HTMLModElement
  kbd: HTMLElement
  keygen: HTMLElement
  label: HTMLLabelElement
  legend: HTMLLegendElement
  li: HTMLLIElement
  link: HTMLLinkElement
  main: HTMLElement
  map: HTMLMapElement
  mark: HTMLElement
  menu: HTMLElement
  menuitem: HTMLElement
  meta: HTMLMetaElement
  meter: HTMLMeterElement
  nav: HTMLElement
  noindex: HTMLElement
  noscript: HTMLElement
  object: HTMLObjectElement
  ol: HTMLOListElement
  optgroup: HTMLOptGroupElement
  option: HTMLOptionElement
  output: HTMLOutputElement
  p: HTMLParagraphElement
  param: HTMLParamElement
  picture: HTMLElement
  pre: HTMLPreElement
  progress: HTMLProgressElement
  q: HTMLQuoteElement
  rp: HTMLElement
  rt: HTMLElement
  ruby: HTMLElement
  s: HTMLElement
  samp: HTMLElement
  search: HTMLElement
  slot: HTMLSlotElement
  script: HTMLScriptElement
  section: HTMLElement
  select: HTMLSelectElement
  small: HTMLElement
  source: HTMLSourceElement
  span: HTMLSpanElement
  strong: HTMLElement
  style: HTMLStyleElement
  sub: HTMLElement
  summary: HTMLElement
  sup: HTMLElement
  table: HTMLTableElement
  template: HTMLTemplateElement
  tbody: HTMLTableSectionElement
  td: HTMLTableDataCellElement
  textarea: HTMLTextAreaElement
  tfoot: HTMLTableSectionElement
  th: HTMLTableHeaderCellElement
  thead: HTMLTableSectionElement
  time: HTMLTimeElement
  title: HTMLTitleElement
  tr: HTMLTableRowElement
  track: HTMLTrackElement
  u: HTMLElement
  ul: HTMLUListElement
  var: HTMLElement
  video: HTMLVideoElement
  wbr: HTMLElement

  // SVG
  svg: SVGSVGElement

  animate: SVGAnimateElement
  animateMotion: SVGElement
  animateTransform: SVGAnimateTransformElement
  circle: SVGCircleElement
  clipPath: SVGClipPathElement
  defs: SVGDefsElement
  desc: SVGDescElement
  ellipse: SVGEllipseElement
  feBlend: SVGFEBlendElement
  feColorMatrix: SVGFEColorMatrixElement
  feComponentTransfer: SVGFEComponentTransferElement
  feComposite: SVGFECompositeElement
  feConvolveMatrix: SVGFEConvolveMatrixElement
  feDiffuseLighting: SVGFEDiffuseLightingElement
  feDisplacementMap: SVGFEDisplacementMapElement
  feDistantLight: SVGFEDistantLightElement
  feDropShadow: SVGFEDropShadowElement
  feFlood: SVGFEFloodElement
  feFuncA: SVGFEFuncAElement
  feFuncB: SVGFEFuncBElement
  feFuncG: SVGFEFuncGElement
  feFuncR: SVGFEFuncRElement
  feGaussianBlur: SVGFEGaussianBlurElement
  feImage: SVGFEImageElement
  feMerge: SVGFEMergeElement
  feMergeNode: SVGFEMergeNodeElement
  feMorphology: SVGFEMorphologyElement
  feOffset: SVGFEOffsetElement
  fePointLight: SVGFEPointLightElement
  feSpecularLighting: SVGFESpecularLightingElement
  feSpotLight: SVGFESpotLightElement
  feTile: SVGFETileElement
  feTurbulence: SVGFETurbulenceElement
  filter: SVGFilterElement
  foreignObject: SVGForeignObjectElement
  g: SVGGElement
  image: SVGImageElement
  line: SVGLineElement
  linearGradient: SVGLinearGradientElement
  marker: SVGMarkerElement
  mask: SVGMaskElement
  metadata: SVGMetadataElement
  mpath: SVGElement
  path: SVGPathElement
  pattern: SVGPatternElement
  polygon: SVGPolygonElement
  polyline: SVGPolylineElement
  radialGradient: SVGRadialGradientElement
  rect: SVGRectElement
  set: SVGSetElement
  stop: SVGStopElement
  switch: SVGSwitchElement
  symbol: SVGSymbolElement
  text: SVGTextElement
  textPath: SVGTextPathElement
  tspan: SVGTSpanElement
  use: SVGUseElement
  view: SVGViewElement
}

export interface IntrinsicElementsAttributes {
  // HTML
  a: Attributes.AnchorHTMLAttributes<HTMLAnchorElement>
  abbr: Attributes.HTMLAttributes<HTMLElement>
  address: Attributes.HTMLAttributes<HTMLElement>
  area: Attributes.AreaHTMLAttributes<HTMLAreaElement>
  article: Attributes.HTMLAttributes<HTMLElement>
  aside: Attributes.HTMLAttributes<HTMLElement>
  audio: Attributes.AudioHTMLAttributes<HTMLAudioElement>
  b: Attributes.HTMLAttributes<HTMLElement>
  base: Attributes.BaseHTMLAttributes<HTMLBaseElement>
  bdi: Attributes.HTMLAttributes<HTMLElement>
  bdo: Attributes.HTMLAttributes<HTMLElement>
  big: Attributes.HTMLAttributes<HTMLElement>
  blockquote: Attributes.BlockquoteHTMLAttributes<HTMLQuoteElement>
  body: Attributes.HTMLAttributes<HTMLBodyElement>
  br: Attributes.HTMLAttributes<HTMLBRElement>
  button: Attributes.ButtonHTMLAttributes<HTMLButtonElement>
  canvas: Attributes.CanvasHTMLAttributes<HTMLCanvasElement>
  caption: Attributes.HTMLAttributes<HTMLElement>
  center: Attributes.HTMLAttributes<HTMLElement>
  cite: Attributes.HTMLAttributes<HTMLElement>
  code: Attributes.HTMLAttributes<HTMLElement>
  col: Attributes.ColHTMLAttributes<HTMLTableColElement>
  colgroup: Attributes.ColgroupHTMLAttributes<HTMLTableColElement>
  data: Attributes.DataHTMLAttributes<HTMLDataElement>
  datalist: Attributes.HTMLAttributes<HTMLDataListElement>
  dd: Attributes.HTMLAttributes<HTMLElement>
  del: Attributes.DelHTMLAttributes<HTMLModElement>
  details: Attributes.DetailsHTMLAttributes<HTMLDetailsElement>
  dfn: Attributes.HTMLAttributes<HTMLElement>
  dialog: Attributes.DialogHTMLAttributes<HTMLDialogElement>
  div: Attributes.HTMLAttributes<HTMLDivElement>
  dl: Attributes.HTMLAttributes<HTMLDListElement>
  dt: Attributes.HTMLAttributes<HTMLElement>
  em: Attributes.HTMLAttributes<HTMLElement>
  embed: Attributes.EmbedHTMLAttributes<HTMLEmbedElement>
  fieldset: Attributes.FieldsetHTMLAttributes<HTMLFieldSetElement>
  figcaption: Attributes.HTMLAttributes<HTMLElement>
  figure: Attributes.HTMLAttributes<HTMLElement>
  footer: Attributes.HTMLAttributes<HTMLElement>
  form: Attributes.FormHTMLAttributes<HTMLFormElement>
  h1: Attributes.HTMLAttributes<HTMLHeadingElement>
  h2: Attributes.HTMLAttributes<HTMLHeadingElement>
  h3: Attributes.HTMLAttributes<HTMLHeadingElement>
  h4: Attributes.HTMLAttributes<HTMLHeadingElement>
  h5: Attributes.HTMLAttributes<HTMLHeadingElement>
  h6: Attributes.HTMLAttributes<HTMLHeadingElement>
  head: Attributes.HTMLAttributes<HTMLHeadElement>
  header: Attributes.HTMLAttributes<HTMLElement>
  hgroup: Attributes.HTMLAttributes<HTMLElement>
  hr: Attributes.HTMLAttributes<HTMLHRElement>
  html: Attributes.HtmlHTMLAttributes<HTMLHtmlElement>
  i: Attributes.HTMLAttributes<HTMLElement>
  iframe: Attributes.IframeHTMLAttributes<HTMLIFrameElement>
  img: Attributes.ImgHTMLAttributes<HTMLImageElement>
  input: Attributes.InputHTMLAttributes<HTMLInputElement>
  ins: Attributes.InsHTMLAttributes<HTMLModElement>
  kbd: Attributes.HTMLAttributes<HTMLElement>
  keygen: Attributes.KeygenHTMLAttributes<HTMLElement>
  label: Attributes.LabelHTMLAttributes<HTMLLabelElement>
  legend: Attributes.HTMLAttributes<HTMLLegendElement>
  li: Attributes.LiHTMLAttributes<HTMLLIElement>
  link: Attributes.LinkHTMLAttributes<HTMLLinkElement>
  main: Attributes.HTMLAttributes<HTMLElement>
  map: Attributes.MapHTMLAttributes<HTMLMapElement>
  mark: Attributes.HTMLAttributes<HTMLElement>
  menu: Attributes.MenuHTMLAttributes<HTMLElement>
  menuitem: Attributes.HTMLAttributes<HTMLElement>
  meta: Attributes.MetaHTMLAttributes<HTMLMetaElement>
  meter: Attributes.MeterHTMLAttributes<HTMLMeterElement>
  nav: Attributes.HTMLAttributes<HTMLElement>
  noindex: Attributes.HTMLAttributes<HTMLElement>
  noscript: Attributes.HTMLAttributes<HTMLElement>
  object: Attributes.ObjectHTMLAttributes<HTMLObjectElement>
  ol: Attributes.OlHTMLAttributes<HTMLOListElement>
  optgroup: Attributes.OptgroupHTMLAttributes<HTMLOptGroupElement>
  option: Attributes.OptionHTMLAttributes<HTMLOptionElement>
  output: Attributes.OutputHTMLAttributes<HTMLOutputElement>
  p: Attributes.HTMLAttributes<HTMLParagraphElement>
  param: Attributes.ParamHTMLAttributes<HTMLParamElement>
  picture: Attributes.HTMLAttributes<HTMLElement>
  pre: Attributes.HTMLAttributes<HTMLPreElement>
  progress: Attributes.ProgressHTMLAttributes<HTMLProgressElement>
  q: Attributes.QuoteHTMLAttributes<HTMLQuoteElement>
  rp: Attributes.HTMLAttributes<HTMLElement>
  rt: Attributes.HTMLAttributes<HTMLElement>
  ruby: Attributes.HTMLAttributes<HTMLElement>
  s: Attributes.HTMLAttributes<HTMLElement>
  samp: Attributes.HTMLAttributes<HTMLElement>
  search: Attributes.HTMLAttributes<HTMLElement>
  slot: Attributes.SlotHTMLAttributes<HTMLSlotElement>
  script: Attributes.ScriptHTMLAttributes<HTMLScriptElement>
  section: Attributes.HTMLAttributes<HTMLElement>
  select: Attributes.SelectHTMLAttributes<HTMLSelectElement>
  small: Attributes.HTMLAttributes<HTMLElement>
  source: Attributes.SourceHTMLAttributes<HTMLSourceElement>
  span: Attributes.HTMLAttributes<HTMLSpanElement>
  strong: Attributes.HTMLAttributes<HTMLElement>
  style: Attributes.StyleHTMLAttributes<HTMLStyleElement>
  sub: Attributes.HTMLAttributes<HTMLElement>
  summary: Attributes.HTMLAttributes<HTMLElement>
  sup: Attributes.HTMLAttributes<HTMLElement>
  table: Attributes.TableHTMLAttributes<HTMLTableElement>
  template: Attributes.HTMLAttributes<HTMLTemplateElement>
  tbody: Attributes.HTMLAttributes<HTMLTableSectionElement>
  td: Attributes.TdHTMLAttributes<HTMLTableDataCellElement>
  textarea: Attributes.TextareaHTMLAttributes<HTMLTextAreaElement>
  tfoot: Attributes.HTMLAttributes<HTMLTableSectionElement>
  th: Attributes.ThHTMLAttributes<HTMLTableHeaderCellElement>
  thead: Attributes.HTMLAttributes<HTMLTableSectionElement>
  time: Attributes.TimeHTMLAttributes<HTMLTimeElement>
  title: Attributes.HTMLAttributes<HTMLTitleElement>
  tr: Attributes.HTMLAttributes<HTMLTableRowElement>
  track: Attributes.TrackHTMLAttributes<HTMLTrackElement>
  u: Attributes.HTMLAttributes<HTMLElement>
  ul: Attributes.HTMLAttributes<HTMLUListElement>
  var: Attributes.HTMLAttributes<HTMLElement>
  video: Attributes.VideoHTMLAttributes<HTMLVideoElement>
  wbr: Attributes.HTMLAttributes<HTMLElement>

  // SVG
  svg: Attributes.SVGAttributes<SVGSVGElement>

  animate: Attributes.SVGAttributes<SVGAnimateElement>
  animateMotion: Attributes.SVGAttributes<SVGElement>
  animateTransform: Attributes.SVGAttributes<SVGAnimateTransformElement>
  circle: Attributes.SVGAttributes<SVGCircleElement>
  clipPath: Attributes.SVGAttributes<SVGClipPathElement>
  defs: Attributes.SVGAttributes<SVGDefsElement>
  desc: Attributes.SVGAttributes<SVGDescElement>
  ellipse: Attributes.SVGAttributes<SVGEllipseElement>
  feBlend: Attributes.SVGAttributes<SVGFEBlendElement>
  feColorMatrix: Attributes.SVGAttributes<SVGFEColorMatrixElement>
  feComponentTransfer: Attributes.SVGAttributes<SVGFEComponentTransferElement>
  feComposite: Attributes.SVGAttributes<SVGFECompositeElement>
  feConvolveMatrix: Attributes.SVGAttributes<SVGFEConvolveMatrixElement>
  feDiffuseLighting: Attributes.SVGAttributes<SVGFEDiffuseLightingElement>
  feDisplacementMap: Attributes.SVGAttributes<SVGFEDisplacementMapElement>
  feDistantLight: Attributes.SVGAttributes<SVGFEDistantLightElement>
  feDropShadow: Attributes.SVGAttributes<SVGFEDropShadowElement>
  feFlood: Attributes.SVGAttributes<SVGFEFloodElement>
  feFuncA: Attributes.SVGAttributes<SVGFEFuncAElement>
  feFuncB: Attributes.SVGAttributes<SVGFEFuncBElement>
  feFuncG: Attributes.SVGAttributes<SVGFEFuncGElement>
  feFuncR: Attributes.SVGAttributes<SVGFEFuncRElement>
  feGaussianBlur: Attributes.SVGAttributes<SVGFEGaussianBlurElement>
  feImage: Attributes.SVGAttributes<SVGFEImageElement>
  feMerge: Attributes.SVGAttributes<SVGFEMergeElement>
  feMergeNode: Attributes.SVGAttributes<SVGFEMergeNodeElement>
  feMorphology: Attributes.SVGAttributes<SVGFEMorphologyElement>
  feOffset: Attributes.SVGAttributes<SVGFEOffsetElement>
  fePointLight: Attributes.SVGAttributes<SVGFEPointLightElement>
  feSpecularLighting: Attributes.SVGAttributes<SVGFESpecularLightingElement>
  feSpotLight: Attributes.SVGAttributes<SVGFESpotLightElement>
  feTile: Attributes.SVGAttributes<SVGFETileElement>
  feTurbulence: Attributes.SVGAttributes<SVGFETurbulenceElement>
  filter: Attributes.SVGAttributes<SVGFilterElement>
  foreignObject: Attributes.SVGAttributes<SVGForeignObjectElement>
  g: Attributes.SVGAttributes<SVGGElement>
  image: Attributes.SVGAttributes<SVGImageElement>
  line: Attributes.SVGAttributes<SVGLineElement>
  linearGradient: Attributes.SVGAttributes<SVGLinearGradientElement>
  marker: Attributes.SVGAttributes<SVGMarkerElement>
  mask: Attributes.SVGAttributes<SVGMaskElement>
  metadata: Attributes.SVGAttributes<SVGMetadataElement>
  mpath: Attributes.SVGAttributes<SVGElement>
  path: Attributes.SVGAttributes<SVGPathElement>
  pattern: Attributes.SVGAttributes<SVGPatternElement>
  polygon: Attributes.SVGAttributes<SVGPolygonElement>
  polyline: Attributes.SVGAttributes<SVGPolylineElement>
  radialGradient: Attributes.SVGAttributes<SVGRadialGradientElement>
  rect: Attributes.SVGAttributes<SVGRectElement>
  set: Attributes.SVGAttributes<SVGSetElement>
  stop: Attributes.SVGAttributes<SVGStopElement>
  switch: Attributes.SVGAttributes<SVGSwitchElement>
  symbol: Attributes.SVGAttributes<SVGSymbolElement>
  text: Attributes.SVGAttributes<SVGTextElement>
  textPath: Attributes.SVGAttributes<SVGTextPathElement>
  tspan: Attributes.SVGAttributes<SVGTSpanElement>
  use: Attributes.SVGAttributes<SVGUseElement>
  view: Attributes.SVGAttributes<SVGViewElement>
}

export type ElementName = keyof IntrinsicElements

export type PickElementType<Tag extends ElementName> = IntrinsicElements[Tag]
