import type * as Attributes from './attributes.js'

export interface IntrinsicElements {
  // HTML
  a: HTMLAnchorElement
  abbr: HTMLElement
  address: HTMLElement
  area: HTMLAreaElement
  article: HTMLElement
  aside: HTMLElement
  audio: HTMLAudioElement
  b: HTMLElement
  base: HTMLBaseElement
  bdi: HTMLElement
  bdo: HTMLElement
  blockquote: HTMLQuoteElement
  body: HTMLBodyElement
  br: HTMLBRElement
  button: HTMLButtonElement
  canvas: HTMLCanvasElement
  caption: HTMLTableCaptionElement
  cite: HTMLElement
  code: HTMLElement
  col: HTMLTableColElement
  colgroup: HTMLTableColElement
  data: HTMLDataElement
  datalist: HTMLDataListElement
  dd: HTMLElement
  del: HTMLModElement
  details: HTMLDetailsElement
  dfn: HTMLElement
  dialog: HTMLDialogElement
  div: HTMLDivElement
  dl: HTMLDListElement
  dt: HTMLElement
  em: HTMLElement
  embed: HTMLEmbedElement
  fieldset: HTMLFieldSetElement
  figcaption: HTMLElement
  figure: HTMLElement
  footer: HTMLElement
  form: HTMLFormElement
  h1: HTMLHeadingElement
  h2: HTMLHeadingElement
  h3: HTMLHeadingElement
  h4: HTMLHeadingElement
  h5: HTMLHeadingElement
  h6: HTMLHeadingElement
  head: HTMLHeadElement
  header: HTMLElement
  hgroup: HTMLElement
  hr: HTMLHRElement
  html: HTMLHtmlElement
  i: HTMLElement
  iframe: HTMLIFrameElement
  img: HTMLImageElement
  input: HTMLInputElement
  ins: HTMLModElement
  kbd: HTMLElement
  label: HTMLLabelElement
  legend: HTMLLegendElement
  li: HTMLLIElement
  link: HTMLLinkElement
  main: HTMLElement
  map: HTMLMapElement
  mark: HTMLElement
  menu: HTMLMenuElement
  meta: HTMLMetaElement
  meter: HTMLMeterElement
  nav: HTMLElement
  noscript: HTMLElement
  object: HTMLObjectElement
  ol: HTMLOListElement
  optgroup: HTMLOptGroupElement
  option: HTMLOptionElement
  output: HTMLOutputElement
  p: HTMLParagraphElement
  picture: HTMLPictureElement
  pre: HTMLPreElement
  progress: HTMLProgressElement
  q: HTMLQuoteElement
  rp: HTMLElement
  rt: HTMLElement
  ruby: HTMLElement
  s: HTMLElement
  samp: HTMLElement
  search: HTMLElement
  slot: HTMLSlotElement
  script: HTMLScriptElement
  section: HTMLElement
  select: HTMLSelectElement
  small: HTMLElement
  source: HTMLSourceElement
  span: HTMLSpanElement
  strong: HTMLElement
  style: HTMLStyleElement
  sub: HTMLElement
  summary: HTMLElement
  sup: HTMLElement
  table: HTMLTableElement
  template: HTMLTemplateElement
  tbody: HTMLTableSectionElement
  td: HTMLTableCellElement
  textarea: HTMLTextAreaElement
  tfoot: HTMLTableSectionElement
  th: HTMLTableCellElement
  thead: HTMLTableSectionElement
  time: HTMLTimeElement
  title: HTMLTitleElement
  tr: HTMLTableRowElement
  track: HTMLTrackElement
  u: HTMLElement
  ul: HTMLUListElement
  var: HTMLElement
  video: HTMLVideoElement
  wbr: HTMLElement
}

export interface IntrinsicElementsAttributes {
  // HTML
  a: Attributes.AnchorHTMLAttributes<HTMLAnchorElement>
  abbr: Attributes.HTMLAttributes<HTMLElement>
  address: Attributes.HTMLAttributes<HTMLElement>
  area: Attributes.AreaHTMLAttributes<HTMLAreaElement>
  article: Attributes.HTMLAttributes<HTMLElement>
  aside: Attributes.HTMLAttributes<HTMLElement>
  audio: Attributes.AudioHTMLAttributes<HTMLAudioElement>
  b: Attributes.HTMLAttributes<HTMLElement>
  base: Attributes.BaseHTMLAttributes<HTMLBaseElement>
  bdi: Attributes.HTMLAttributes<HTMLElement>
  bdo: Attributes.HTMLAttributes<HTMLElement>
  blockquote: Attributes.BlockquoteHTMLAttributes<HTMLQuoteElement>
  body: Attributes.HTMLAttributes<HTMLBodyElement>
  br: Attributes.HTMLAttributes<HTMLBRElement>
  button: Attributes.ButtonHTMLAttributes<HTMLButtonElement>
  canvas: Attributes.CanvasHTMLAttributes<HTMLCanvasElement>
  caption: Attributes.HTMLAttributes<HTMLTableCaptionElement>
  cite: Attributes.HTMLAttributes<HTMLElement>
  code: Attributes.HTMLAttributes<HTMLElement>
  col: Attributes.ColHTMLAttributes<HTMLTableColElement>
  colgroup: Attributes.ColgroupHTMLAttributes<HTMLTableColElement>
  data: Attributes.DataHTMLAttributes<HTMLDataElement>
  datalist: Attributes.HTMLAttributes<HTMLDataListElement>
  dd: Attributes.HTMLAttributes<HTMLElement>
  del: Attributes.DelHTMLAttributes<HTMLModElement>
  details: Attributes.DetailsHTMLAttributes<HTMLDetailsElement>
  dfn: Attributes.HTMLAttributes<HTMLElement>
  dialog: Attributes.DialogHTMLAttributes<HTMLDialogElement>
  div: Attributes.HTMLAttributes<HTMLDivElement>
  dl: Attributes.HTMLAttributes<HTMLDListElement>
  dt: Attributes.HTMLAttributes<HTMLElement>
  em: Attributes.HTMLAttributes<HTMLElement>
  embed: Attributes.EmbedHTMLAttributes<HTMLEmbedElement>
  fieldset: Attributes.FieldsetHTMLAttributes<HTMLFieldSetElement>
  figcaption: Attributes.HTMLAttributes<HTMLElement>
  figure: Attributes.HTMLAttributes<HTMLElement>
  footer: Attributes.HTMLAttributes<HTMLElement>
  form: Attributes.FormHTMLAttributes<HTMLFormElement>
  h1: Attributes.HTMLAttributes<HTMLHeadingElement>
  h2: Attributes.HTMLAttributes<HTMLHeadingElement>
  h3: Attributes.HTMLAttributes<HTMLHeadingElement>
  h4: Attributes.HTMLAttributes<HTMLHeadingElement>
  h5: Attributes.HTMLAttributes<HTMLHeadingElement>
  h6: Attributes.HTMLAttributes<HTMLHeadingElement>
  head: Attributes.HTMLAttributes<HTMLHeadElement>
  header: Attributes.HTMLAttributes<HTMLElement>
  hgroup: Attributes.HTMLAttributes<HTMLElement>
  hr: Attributes.HTMLAttributes<HTMLHRElement>
  html: Attributes.HtmlHTMLAttributes<HTMLHtmlElement>
  i: Attributes.HTMLAttributes<HTMLElement>
  iframe: Attributes.IframeHTMLAttributes<HTMLIFrameElement>
  img: Attributes.ImgHTMLAttributes<HTMLImageElement>
  input: Attributes.InputHTMLAttributes<HTMLInputElement>
  ins: Attributes.InsHTMLAttributes<HTMLModElement>
  kbd: Attributes.HTMLAttributes<HTMLElement>
  label: Attributes.LabelHTMLAttributes<HTMLLabelElement>
  legend: Attributes.HTMLAttributes<HTMLLegendElement>
  li: Attributes.LiHTMLAttributes<HTMLLIElement>
  link: Attributes.LinkHTMLAttributes<HTMLLinkElement>
  main: Attributes.HTMLAttributes<HTMLElement>
  map: Attributes.MapHTMLAttributes<HTMLMapElement>
  mark: Attributes.HTMLAttributes<HTMLElement>
  menu: Attributes.MenuHTMLAttributes<HTMLMenuElement>
  meta: Attributes.MetaHTMLAttributes<HTMLMetaElement>
  meter: Attributes.MeterHTMLAttributes<HTMLMeterElement>
  nav: Attributes.HTMLAttributes<HTMLElement>
  noscript: Attributes.HTMLAttributes<HTMLElement>
  object: Attributes.ObjectHTMLAttributes<HTMLObjectElement>
  ol: Attributes.OlHTMLAttributes<HTMLOListElement>
  optgroup: Attributes.OptgroupHTMLAttributes<HTMLOptGroupElement>
  option: Attributes.OptionHTMLAttributes<HTMLOptionElement>
  output: Attributes.OutputHTMLAttributes<HTMLOutputElement>
  p: Attributes.HTMLAttributes<HTMLParagraphElement>
  picture: Attributes.HTMLAttributes<HTMLPictureElement>
  pre: Attributes.HTMLAttributes<HTMLPreElement>
  progress: Attributes.ProgressHTMLAttributes<HTMLProgressElement>
  q: Attributes.QuoteHTMLAttributes<HTMLQuoteElement>
  rp: Attributes.HTMLAttributes<HTMLElement>
  rt: Attributes.HTMLAttributes<HTMLElement>
  ruby: Attributes.HTMLAttributes<HTMLElement>
  s: Attributes.HTMLAttributes<HTMLElement>
  samp: Attributes.HTMLAttributes<HTMLElement>
  search: Attributes.HTMLAttributes<HTMLElement>
  slot: Attributes.SlotHTMLAttributes<HTMLSlotElement>
  script: Attributes.ScriptHTMLAttributes<HTMLScriptElement>
  section: Attributes.HTMLAttributes<HTMLElement>
  select: Attributes.SelectHTMLAttributes<HTMLSelectElement>
  small: Attributes.HTMLAttributes<HTMLElement>
  source: Attributes.SourceHTMLAttributes<HTMLSourceElement>
  span: Attributes.HTMLAttributes<HTMLSpanElement>
  strong: Attributes.HTMLAttributes<HTMLElement>
  style: Attributes.StyleHTMLAttributes<HTMLStyleElement>
  sub: Attributes.HTMLAttributes<HTMLElement>
  summary: Attributes.HTMLAttributes<HTMLElement>
  sup: Attributes.HTMLAttributes<HTMLElement>
  table: Attributes.TableHTMLAttributes<HTMLTableElement>
  template: Attributes.HTMLAttributes<HTMLTemplateElement>
  tbody: Attributes.HTMLAttributes<HTMLTableSectionElement>
  td: Attributes.TdHTMLAttributes<HTMLTableCellElement>
  textarea: Attributes.TextareaHTMLAttributes<HTMLTextAreaElement>
  tfoot: Attributes.HTMLAttributes<HTMLTableSectionElement>
  th: Attributes.ThHTMLAttributes<HTMLTableCellElement>
  thead: Attributes.HTMLAttributes<HTMLTableSectionElement>
  time: Attributes.TimeHTMLAttributes<HTMLTimeElement>
  title: Attributes.HTMLAttributes<HTMLTitleElement>
  tr: Attributes.HTMLAttributes<HTMLTableRowElement>
  track: Attributes.TrackHTMLAttributes<HTMLTrackElement>
  u: Attributes.HTMLAttributes<HTMLElement>
  ul: Attributes.HTMLAttributes<HTMLUListElement>
  var: Attributes.HTMLAttributes<HTMLElement>
  video: Attributes.VideoHTMLAttributes<HTMLVideoElement>
  wbr: Attributes.HTMLAttributes<HTMLElement>
}

export type ElementName = keyof IntrinsicElements

export type PickElementType<Tag extends ElementName> = IntrinsicElements[Tag]
