import {
  createVoidElement,
  createVoidElementFactory,
  createElement,
  createElementFactory
} from '../internals/index.js'

export {
  createVoidElement,
  createVoidElementFactory,
  createElement,
  createElementFactory
}

// HTML
export const a = /* @__PURE__ */ createElementFactory('a')
export const abbr = /* @__PURE__ */ createElementFactory('abbr')
export const address = /* @__PURE__ */ createElementFactory('address')
export const area = /* @__PURE__ */ createVoidElementFactory('area')
export const article = /* @__PURE__ */ createElementFactory('article')
export const aside = /* @__PURE__ */ createElementFactory('aside')
export const audio = /* @__PURE__ */ createElementFactory('audio')
export const b = /* @__PURE__ */ createElementFactory('b')
export const base = /* @__PURE__ */ createVoidElementFactory('base')
export const bdi = /* @__PURE__ */ createElementFactory('bdi')
export const bdo = /* @__PURE__ */ createElementFactory('bdo')
export const blockquote = /* @__PURE__ */ createElementFactory('blockquote')
export const body = /* @__PURE__ */ createElementFactory('body')
export const br = /* @__PURE__ */ createVoidElementFactory('br')
export const button = /* @__PURE__ */ createElementFactory('button')
export const canvas = /* @__PURE__ */ createElementFactory('canvas')
export const caption = /* @__PURE__ */ createElementFactory('caption')
export const cite = /* @__PURE__ */ createElementFactory('cite')
export const code = /* @__PURE__ */ createElementFactory('code')
export const col = /* @__PURE__ */ createVoidElementFactory('col')
export const colgroup = /* @__PURE__ */ createElementFactory('colgroup')
export const data = /* @__PURE__ */ createElementFactory('data')
export const datalist = /* @__PURE__ */ createElementFactory('datalist')
export const dd = /* @__PURE__ */ createElementFactory('dd')
export const del = /* @__PURE__ */ createElementFactory('del')
export const details = /* @__PURE__ */ createElementFactory('details')
export const dfn = /* @__PURE__ */ createElementFactory('dfn')
export const dialog = /* @__PURE__ */ createElementFactory('dialog')
export const div = /* @__PURE__ */ createElementFactory('div')
export const dl = /* @__PURE__ */ createElementFactory('dl')
export const dt = /* @__PURE__ */ createElementFactory('dt')
export const em = /* @__PURE__ */ createElementFactory('em')
export const embed = /* @__PURE__ */ createVoidElementFactory('embed')
export const fieldset = /* @__PURE__ */ createElementFactory('fieldset')
export const figcaption = /* @__PURE__ */ createElementFactory('figcaption')
export const figure = /* @__PURE__ */ createElementFactory('figure')
export const footer = /* @__PURE__ */ createElementFactory('footer')
export const form = /* @__PURE__ */ createElementFactory('form')
export const h1 = /* @__PURE__ */ createElementFactory('h1')
export const h2 = /* @__PURE__ */ createElementFactory('h2')
export const h3 = /* @__PURE__ */ createElementFactory('h3')
export const h4 = /* @__PURE__ */ createElementFactory('h4')
export const h5 = /* @__PURE__ */ createElementFactory('h5')
export const h6 = /* @__PURE__ */ createElementFactory('h6')
export const head = /* @__PURE__ */ createElementFactory('head')
export const header = /* @__PURE__ */ createElementFactory('header')
export const hgroup = /* @__PURE__ */ createElementFactory('hgroup')
export const hr = /* @__PURE__ */ createVoidElementFactory('hr')
export const html = /* @__PURE__ */ createElementFactory('html')
export const i = /* @__PURE__ */ createElementFactory('i')
export const iframe = /* @__PURE__ */ createElementFactory('iframe')
export const img = /* @__PURE__ */ createVoidElementFactory('img')
export const input = /* @__PURE__ */ createVoidElementFactory('input')
export const ins = /* @__PURE__ */ createElementFactory('ins')
export const kbd = /* @__PURE__ */ createElementFactory('kbd')
export const label = /* @__PURE__ */ createElementFactory('label')
export const legend = /* @__PURE__ */ createElementFactory('legend')
export const li = /* @__PURE__ */ createElementFactory('li')
export const link = /* @__PURE__ */ createVoidElementFactory('link')
export const main = /* @__PURE__ */ createElementFactory('main')
export const map = /* @__PURE__ */ createElementFactory('map')
export const mark = /* @__PURE__ */ createElementFactory('mark')
export const menu = /* @__PURE__ */ createElementFactory('menu')
export const meta = /* @__PURE__ */ createVoidElementFactory('meta')
export const meter = /* @__PURE__ */ createElementFactory('meter')
export const nav = /* @__PURE__ */ createElementFactory('nav')
export const noscript = /* @__PURE__ */ createElementFactory('noscript')
export const object = /* @__PURE__ */ createElementFactory('object')
export const ol = /* @__PURE__ */ createElementFactory('ol')
export const optgroup = /* @__PURE__ */ createElementFactory('optgroup')
export const option = /* @__PURE__ */ createElementFactory('option')
export const output = /* @__PURE__ */ createElementFactory('output')
export const p = /* @__PURE__ */ createElementFactory('p')
export const picture = /* @__PURE__ */ createElementFactory('picture')
export const pre = /* @__PURE__ */ createElementFactory('pre')
export const progress = /* @__PURE__ */ createElementFactory('progress')
export const q = /* @__PURE__ */ createElementFactory('q')
export const rp = /* @__PURE__ */ createElementFactory('rp')
export const rt = /* @__PURE__ */ createElementFactory('rt')
export const ruby = /* @__PURE__ */ createElementFactory('ruby')
export const s = /* @__PURE__ */ createElementFactory('s')
export const samp = /* @__PURE__ */ createElementFactory('samp')
export const search = /* @__PURE__ */ createElementFactory('search')
export const slot = /* @__PURE__ */ createElementFactory('slot')
export const script = /* @__PURE__ */ createElementFactory('script')
export const section = /* @__PURE__ */ createElementFactory('section')
export const select = /* @__PURE__ */ createElementFactory('select')
export const small = /* @__PURE__ */ createElementFactory('small')
export const source = /* @__PURE__ */ createVoidElementFactory('source')
export const span = /* @__PURE__ */ createElementFactory('span')
export const strong = /* @__PURE__ */ createElementFactory('strong')
export const style = /* @__PURE__ */ createElementFactory('style')
export const sub = /* @__PURE__ */ createElementFactory('sub')
export const summary = /* @__PURE__ */ createElementFactory('summary')
export const sup = /* @__PURE__ */ createElementFactory('sup')
export const table = /* @__PURE__ */ createElementFactory('table')
export const template = /* @__PURE__ */ createElementFactory('template')
export const tbody = /* @__PURE__ */ createElementFactory('tbody')
export const td = /* @__PURE__ */ createElementFactory('td')
export const textarea = /* @__PURE__ */ createElementFactory('textarea')
export const tfoot = /* @__PURE__ */ createElementFactory('tfoot')
export const th = /* @__PURE__ */ createElementFactory('th')
export const thead = /* @__PURE__ */ createElementFactory('thead')
export const time = /* @__PURE__ */ createElementFactory('time')
export const title = /* @__PURE__ */ createElementFactory('title')
export const tr = /* @__PURE__ */ createElementFactory('tr')
export const track = /* @__PURE__ */ createVoidElementFactory('track')
export const u = /* @__PURE__ */ createElementFactory('u')
export const ul = /* @__PURE__ */ createElementFactory('ul')

const htmlVar = /* @__PURE__ */ createElementFactory('var')

export { htmlVar as var }

export const video = /* @__PURE__ */ createElementFactory('video')
export const wbr = /* @__PURE__ */ createVoidElementFactory('wbr')
