import {
  createVoidElement,
  createVoidElementFactory,
  createElement,
  createElementFactory
} from '../internals/index.js'

export {
  createVoidElement,
  createVoidElementFactory,
  createElement,
  createElementFactory
}

// HTML
export const a = createElementFactory('a')
export const abbr = createElementFactory('abbr')
export const address = createElementFactory('address')
export const area = createVoidElementFactory('area')
export const article = createElementFactory('article')
export const aside = createElementFactory('aside')
export const audio = createElementFactory('audio')
export const b = createElementFactory('b')
export const base = createVoidElementFactory('base')
export const bdi = createElementFactory('bdi')
export const bdo = createElementFactory('bdo')
export const big = createElementFactory('big')
export const blockquote = createElementFactory('blockquote')
export const body = createElementFactory('body')
export const br = createVoidElementFactory('br')
export const button = createElementFactory('button')
export const canvas = createElementFactory('canvas')
export const caption = createElementFactory('caption')
export const center = createElementFactory('center')
export const cite = createElementFactory('cite')
export const code = createElementFactory('code')
export const col = createVoidElementFactory('col')
export const colgroup = createElementFactory('colgroup')
export const data = createElementFactory('data')
export const datalist = createElementFactory('datalist')
export const dd = createElementFactory('dd')
export const del = createElementFactory('del')
export const details = createElementFactory('details')
export const dfn = createElementFactory('dfn')
export const dialog = createElementFactory('dialog')
export const div = createElementFactory('div')
export const dl = createElementFactory('dl')
export const dt = createElementFactory('dt')
export const em = createElementFactory('em')
export const embed = createVoidElementFactory('embed')
export const fieldset = createElementFactory('fieldset')
export const figcaption = createElementFactory('figcaption')
export const figure = createElementFactory('figure')
export const footer = createElementFactory('footer')
export const form = createElementFactory('form')
export const h1 = createElementFactory('h1')
export const h2 = createElementFactory('h2')
export const h3 = createElementFactory('h3')
export const h4 = createElementFactory('h4')
export const h5 = createElementFactory('h5')
export const h6 = createElementFactory('h6')
export const head = createElementFactory('head')
export const header = createElementFactory('header')
export const hgroup = createElementFactory('hgroup')
export const hr = createVoidElementFactory('hr')
export const html = createElementFactory('html')
export const i = createElementFactory('i')
export const iframe = createElementFactory('iframe')
export const img = createVoidElementFactory('img')
export const input = createVoidElementFactory('input')
export const ins = createElementFactory('ins')
export const kbd = createElementFactory('kbd')
export const keygen = createElementFactory('keygen')
export const label = createElementFactory('label')
export const legend = createElementFactory('legend')
export const li = createElementFactory('li')
export const link = createVoidElementFactory('link')
export const main = createElementFactory('main')
export const map = createElementFactory('map')
export const mark = createElementFactory('mark')
export const menu = createElementFactory('menu')
export const menuitem = createElementFactory('menuitem')
export const meta = createVoidElementFactory('meta')
export const meter = createElementFactory('meter')
export const nav = createElementFactory('nav')
export const noindex = createElementFactory('noindex')
export const noscript = createElementFactory('noscript')
export const object = createElementFactory('object')
export const ol = createElementFactory('ol')
export const optgroup = createElementFactory('optgroup')
export const option = createElementFactory('option')
export const output = createElementFactory('output')
export const p = createElementFactory('p')
export const param = createVoidElementFactory('param')
export const picture = createElementFactory('picture')
export const pre = createElementFactory('pre')
export const progress = createElementFactory('progress')
export const q = createElementFactory('q')
export const rp = createElementFactory('rp')
export const rt = createElementFactory('rt')
export const ruby = createElementFactory('ruby')
export const s = createElementFactory('s')
export const samp = createElementFactory('samp')
export const search = createElementFactory('search')
export const slot = createElementFactory('slot')
export const script = createElementFactory('script')
export const section = createElementFactory('section')
export const select = createElementFactory('select')
export const small = createElementFactory('small')
export const source = createVoidElementFactory('source')
export const span = createElementFactory('span')
export const strong = createElementFactory('strong')
export const style = createElementFactory('style')
export const sub = createElementFactory('sub')
export const summary = createElementFactory('summary')
export const sup = createElementFactory('sup')
export const table = createElementFactory('table')
export const template = createElementFactory('template')
export const tbody = createElementFactory('tbody')
export const td = createElementFactory('td')
export const textarea = createElementFactory('textarea')
export const tfoot = createElementFactory('tfoot')
export const th = createElementFactory('th')
export const thead = createElementFactory('thead')
export const time = createElementFactory('time')
export const title = createElementFactory('title')
export const tr = createElementFactory('tr')
export const track = createVoidElementFactory('track')
export const u = createElementFactory('u')
export const ul = createElementFactory('ul')

const htmlVar = createElementFactory('var')

export { htmlVar as var }

export const video = createElementFactory('video')
export const wbr = createVoidElementFactory('wbr')

// SVG
export const svg = createElementFactory('svg')

export const animate = createVoidElementFactory('animate')
export const animateMotion = createVoidElementFactory('animateMotion')
export const animateTransform = createVoidElementFactory('animateTransform')
export const circle = createVoidElementFactory('circle')
export const clipPath = createElementFactory('clipPath')
export const defs = createElementFactory('defs')
export const desc = createElementFactory('desc')
export const ellipse = createVoidElementFactory('ellipse')
export const feBlend = createElementFactory('feBlend')
export const feColorMatrix = createElementFactory('feColorMatrix')
export const feComponentTransfer = createElementFactory('feComponentTransfer')
export const feComposite = createElementFactory('feComposite')
export const feConvolveMatrix = createElementFactory('feConvolveMatrix')
export const feDiffuseLighting = createElementFactory('feDiffuseLighting')
export const feDisplacementMap = createElementFactory('feDisplacementMap')
export const feDistantLight = createElementFactory('feDistantLight')
export const feDropShadow = createElementFactory('feDropShadow')
export const feFlood = createElementFactory('feFlood')
export const feFuncA = createElementFactory('feFuncA')
export const feFuncB = createElementFactory('feFuncB')
export const feFuncG = createElementFactory('feFuncG')
export const feFuncR = createElementFactory('feFuncR')
export const feGaussianBlur = createElementFactory('feGaussianBlur')
export const feImage = createElementFactory('feImage')
export const feMerge = createElementFactory('feMerge')
export const feMergeNode = createElementFactory('feMergeNode')
export const feMorphology = createElementFactory('feMorphology')
export const feOffset = createElementFactory('feOffset')
export const fePointLight = createElementFactory('fePointLight')
export const feSpecularLighting = createElementFactory('feSpecularLighting')
export const feSpotLight = createElementFactory('feSpotLight')
export const feTile = createElementFactory('feTile')
export const feTurbulence = createElementFactory('feTurbulence')
export const filter = createElementFactory('filter')
export const foreignObject = createElementFactory('foreignObject')
export const g = createElementFactory('g')
export const image = createVoidElementFactory('image')
export const line = createVoidElementFactory('line')
export const linearGradient = createElementFactory('linearGradient')
export const marker = createElementFactory('marker')
export const mask = createElementFactory('mask')
export const metadata = createElementFactory('metadata')
export const mpath = createVoidElementFactory('mpath')
export const path = createVoidElementFactory('path')
export const pattern = createElementFactory('pattern')
export const polygon = createVoidElementFactory('polygon')
export const polyline = createVoidElementFactory('polyline')
export const radialGradient = createElementFactory('radialGradient')
export const rect = createVoidElementFactory('rect')
export const set = createVoidElementFactory('set')
export const stop = createElementFactory('stop')

const svgSwitch = createElementFactory('switch')

export { svgSwitch as switch }

export const symbol = createElementFactory('symbol')
export const text = createElementFactory('text')
export const textPath = createElementFactory('textPath')
export const tspan = createElementFactory('tspan')
export const use = createVoidElementFactory('use')
export const view = createElementFactory('view')
